/**
 * Country Flag Mapping
 * 
 * Maps country names to flag emojis
 */

export const COUNTRY_FLAGS: Record<string, string> = {
  'England': '🇬🇧',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Northern Ireland': '🇬🇧',
  'Brazil': '🇧🇷',
  'Argentina': '🇦🇷',
  'France': '🇫🇷',
  'Spain': '🇪🇸',
  'Germany': '🇩🇪',
  'Italy': '🇮🇹',
  'Portugal': '🇵🇹',
  'Netherlands': '🇳🇱',
  'Belgium': '🇧🇪',
  'Croatia': '🇭🇷',
  'Denmark': '🇩🇰',
  'Norway': '🇳🇴',
  'Sweden': '🇸🇪',
  'Poland': '🇵🇱',
  'Czech Republic': '🇨🇿',
  'Austria': '🇦🇹',
  'Switzerland': '🇨🇭',
  'Turkey': '🇹🇷',
  'Greece': '🇬🇷',
  'Russia': '🇷🇺',
  'Ukraine': '🇺🇦',
  'Serbia': '🇷🇸',
  'Slovakia': '🇸🇰',
  'Slovenia': '🇸🇮',
  'Hungary': '🇭🇺',
  'Romania': '🇷🇴',
  'Bulgaria': '🇧🇬',
  'Egypt': '🇪🇬',
  'Nigeria': '🇳🇬',
  'Senegal': '🇸🇳',
  'Ghana': '🇬🇭',
  'Ivory Coast': '🇨🇮',
  'Cameroon': '🇨🇲',
  'Morocco': '🇲🇦',
  'Algeria': '🇩🇿',
  'Tunisia': '🇹🇳',
  'South Africa': '🇿🇦',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'China': '🇨🇳',
  'Australia': '🇦🇺',
  'New Zealand': '🇳🇿',
  'USA': '🇺🇸',
  'Canada': '🇨🇦',
  'Mexico': '🇲🇽',
  'Colombia': '🇨🇴',
  'Chile': '🇨🇱',
  'Uruguay': '🇺🇾',
  'Paraguay': '🇵🇾',
  'Peru': '🇵🇪',
  'Ecuador': '🇪🇨',
  'Venezuela': '🇻🇪',
  'Bolivia': '🇧🇴',
  'Costa Rica': '🇨🇷',
  'Panama': '🇵🇦',
  'Honduras': '🇭🇳',
  'Jamaica': '🇯🇲',
  'Trinidad and Tobago': '🇹🇹',
  'Iran': '🇮🇷',
  'Saudi Arabia': '🇸🇦',
  'UAE': '🇦🇪',
  'Qatar': '🇶🇦',
  'Kuwait': '🇰🇼',
  'Iraq': '🇮🇶',
  'Israel': '🇮🇱',
  'Lebanon': '🇱🇧',
  'Syria': '🇸🇾',
  'Jordan': '🇯🇴',
  'Yemen': '🇾🇪',
  'Oman': '🇴🇲',
  'Bahrain': '🇧🇭',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Indonesia': '🇮🇩',
  'Malaysia': '🇲🇾',
  'Singapore': '🇸🇬',
  'Philippines': '🇵🇭',
  'Myanmar': '🇲🇲',
  'Cambodia': '🇰🇭',
  'Laos': '🇱🇦',
  'Brunei': '🇧🇳',
  'East Timor': '🇹🇱',
  'Bangladesh': '🇧🇩',
  'Sri Lanka': '🇱🇰',
  'Nepal': '🇳🇵',
  'Bhutan': '🇧🇹',
  'Maldives': '🇲🇻',
  'Afghanistan': '🇦🇫',
  'Pakistan': '🇵🇰',
  'India': '🇮🇳',
  'Mongolia': '🇲🇳',
  'Kazakhstan': '🇰🇿',
  'Uzbekistan': '🇺🇿',
  'Kyrgyzstan': '🇰🇬',
  'Tajikistan': '🇹🇯',
  'Turkmenistan': '🇹🇲',
  'Azerbaijan': '🇦🇿',
  'Armenia': '🇦🇲',
  'Georgia': '🇬🇪',
  'Moldova': '🇲🇩',
  'Belarus': '🇧🇾',
  'Lithuania': '🇱🇹',
  'Latvia': '🇱🇻',
  'Estonia': '🇪🇪',
  'Finland': '🇫🇮',
  'Iceland': '🇮🇸',
  'Ireland': '🇮🇪',
  'Luxembourg': '🇱🇺',
  'Malta': '🇲🇹',
  'Cyprus': '🇨🇾',
  'Albania': '🇦🇱',
  'Bosnia and Herzegovina': '🇧🇦',
  'North Macedonia': '🇲🇰',
  'Montenegro': '🇲🇪',
  'Kosovo': '🇽🇰',
  'Andorra': '🇦🇩',
  'San Marino': '🇸🇲',
  'Liechtenstein': '🇱🇮',
  'Monaco': '🇲🇨',
  'Vatican City': '🇻🇦',
  'Unknown': '🌍'
}

/**
 * Get country flag emoji
 */
export function getCountryFlag(countryName: string): string {
  return COUNTRY_FLAGS[countryName] || COUNTRY_FLAGS['Unknown']
}

